version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck  # covers many gosimple checks
    - unused
    - ineffassign
    - misspell
    - revive
    - gocyclo
    - dupl
    - unparam
    - nakedret
    - goconst
    - gocritic
  disable:
    - lll

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      # optional: local-prefixes:
      #   - github.com/yourorg/yourrepo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
