services:
  redis:
    image: public.ecr.aws/docker/library/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  postgres:
    image: public.ecr.aws/docker/library/postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bonsai
      POSTGRES_MULTIPLE_DATABASES: bonsai,bonsai_test
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  redis-data:
  pg-data:
